const DATA={"dog": ["Buddy", "Max", "Luna", "Bella", "Charlie", "Daisy", "Cooper", "Milo", "Bailey", "Rocky", "Scout", "Maple", "Ranger", "Oakley", "Pepper", "Waffles", "Tucker", "Nala", "Ruby", "Finn"], "cat": ["Luna", "Milo", "Oliver", "Leo", "Nala", "Cleo", "Mochi", "Willow", "Simba", "Pepper", "Jasper", "Misty", "Sushi", "Pumpkin", "Socks", "Nova", "Ziggy", "Bella", "Hazel", "Binx"], "parrot": ["Kiwi", "Mango", "Rio", "Sunny", "Echo", "Pico", "Zazu", "Skittles", "Peanut", "Coco", "Jade", "Tiki", "Bubbles", "Pepper", "Blu", "Salsa", "Kiki", "Tango", "Papaya", "Jazz"], "horse": ["Spirit", "Dakota", "Star", "Willow", "Storm", "Apollo", "Bella", "Shadow", "Cinnamon", "Duke", "River", "Blaze", "Rosie", "Maverick", "Ruby", "Comet", "Sage", "Majesty", "Scout", "Athena"], "rabbit": ["Bunny", "Thumper", "Clover", "Mochi", "Snowball", "Hazel", "Peanut", "Daisy", "Nibbles", "Cotton", "Oreo", "Biscuit", "Flopsy", "Poppy", "Maple", "Toffee", "Bubbles", "Willow", "Coco", "Lily"], "fish": ["Bubbles", "Nemo", "Splash", "Goldie", "Coral", "Finley", "Blue", "Sushi", "Pearl", "Dory", "Marina", "Ripple", "Sunny", "Aqua", "Guppy", "Wave", "Captain", "Pebbles", "Cleo", "Neptune"], "hamster": ["Peanut", "Nibbles", "Mochi", "Cookie", "Pip", "Coco", "Biscuit", "Tiny", "Oreo", "Poppy", "Pumpkin", "Hazel", "Cheeks", "Button", "Waffles", "Toffee", "Bean", "Muffin", "Maple", "Daisy"], "turtle": ["Shelly", "Tank", "Pebble", "Moss", "Speedy", "Atlas", "Crush", "Terra", "Franklin", "Rocky", "Sage", "Clover", "Tilly", "Squirt", "Boulder", "Olive", "Marble", "River", "Yoda", "Nori"]};const STYLES=["cute", "unique", "funny", "classic", "food", "nature", "royal", "western", "trendy", "short"];const TRAITS=["playful", "calm", "brave", "smart", "tiny", "gentle", "energetic", "lazy", "sweet", "sassy"];
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function gen(){
 let pet=document.getElementById('pet')?.value||'dog';
 let style=document.getElementById('style')?.value||'cute';
 let trait=document.getElementById('trait')?.value||'playful';
 let base=DATA[pet]||DATA.dog; let out=[];
 let extras={cute:['Mochi','Biscuit','Sunny','Poppy','Coco'],unique:['Ziggy','Nova','Atlas','Echo','Indie'],funny:['Pickles','Waffles','Noodle','Tater','Burrito'],classic:['Max','Bella','Charlie','Lucy','Buddy'],food:['Cookie','Pepper','Pumpkin','Bean','Honey'],nature:['River','Clover','Maple','Sage','Storm'],royal:['Duke','King','Queenie','Athena','Prince'],western:['Ranger','Dakota','Scout','Bandit','Tex'],trendy:['Luna','Milo','Nova','Finn','Ruby'],short:['Ace','Blu','Pip','Leo','Rio']};
 for(let i=0;i<16;i++){let arr=(i%2 && extras[style])?extras[style]:base; let name=pick(arr); if(!out.find(x=>x.name==name)) out.push({name:name,tag:style+' name for a '+trait+' '+pet,meaning:'Easy to call, memorable, and friendly for American pet owners.'});}
 document.getElementById('results').innerHTML=out.map(x=>'<div class="card"><div class="name">'+x.name+'</div><div class="meta">'+x.tag+'</div><p>'+x.meaning+'</p></div>').join('');
}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('generate')?.addEventListener('click',gen);gen();});
